# -*- coding: utf-8 -*-
"""FinRL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2reQmzIBOfKOL1DhzY3W5fAoVtAwsoG

**Install required libraries**
"""

pip install finrl

pip install stable-baselines3 tensorflow matplotlib pandas numpy scikit-learn

pip install alpaca-trade-api

pip install exchange-calendars

pip install stockstats

pip install wrds

import gym
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.meta.data_processor import DataProcessor
from finrl.agents.stablebaselines3.models import DRLAgent
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Basic code for FinRL environment setup**"""

import yfinance as yf

# Define symbols for RBC, TD Bank, and Scotiabank
symbols = ["RY.TO", "TD.TO", "BNS.TO"]

# Download historical data from Yahoo Finance
data = yf.download(tickers, start="2021-01-01", end="2023-01-01", group_by='ticker')

#  column names to check the available data
for ticker in tickers:
    print(f"{ticker} columns: ", data[ticker].columns)

# TO check  'Adj Close' and fallback to 'Close' if not available
data = {ticker: data[ticker].get('Adj Close', data[ticker]['Close']) for ticker in tickers}

print(data)

import pandas as pd

df = pd.DataFrame(data)
print(df.head())  # Display the first few rows

# Calculate daily returns
daily_returns = df.pct_change().dropna()
print(daily_returns.head())

import matplotlib.pyplot as plt

# Plot closing prices
df.plot(figsize=(12, 6), title="Closing Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend(title="symbol")
plt.show()

# Calculate correlation matrix
correlation_matrix = daily_returns.corr()
print(correlation_matrix)

# Visualize the correlation matrix
import seaborn as sns

sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix of Returns")
plt.show()

# Calculate portfolio returns assuming equal weight
portfolio_returns = daily_returns.mean(axis=1)  # Equal weighting
cumulative_returns = (1 + portfolio_returns).cumprod()
print(cumulative_returns)

# Plot cumulative returns
cumulative_returns.plot(figsize=(12, 6), title="Cumulative Returns of Equal-Weighted Portfolio")
plt.xlabel("Date")
plt.ylabel("Cumulative Returns")
plt.show()

# Save the DataFrame to a CSV file
df.to_csv("stock_prices.csv")
daily_returns.to_csv("daily_returns.csv")